### ISSUE TITLE
Crashing on Android on RN 0.47.2

### ISSUE THREAD

**Issue by luco** [bgryszko/react-native-circular-progress#93] opened 2017-10-20 17:12 UTC
Anyone with this?
Just crashes the app.

I searched for PR, but I didn't find anything.

**Comment by inspireui** [comment] 2017-10-21 08:11
yes, crashed on Android "undefined is not an object evaluating '_react2.PropTypes.number'"
RN 0.49.3

**Comment by luco** [comment] 2017-10-23 16:07
@inspireui How are you getting this error? I can't even get any error. It just crashes.

**Comment by dantranv** [comment] 2017-11-07 08:27
Found issue, it was caused by View.propTypes.style on both js files.

AnimatedCircularProgress.propTypes = {
  style: **View.propTypes.style**,
  size: PropTypes.number.isRequired,
  fill: PropTypes.number,
  prefill: PropTypes.number,
  width: PropTypes.number.isRequired,
  tintColor: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  backgroundColor: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  tension: PropTypes.number,
  friction: PropTypes.number
}

View.propTypes.style should be **PropTypes.style**

Tested and confirmed work fine on RN 0.49

**Comment by dantranv** [comment] 2017-11-07 08:38
You need to replace '**View.propTypes.style**' with '**ViewPropTypes.style**', also remember to include ViewPropTypes: import { ViewPropTypes } from 'react-native';

Tested on RN 0.49

**Comment by markusl** [comment] 2017-11-20 12:40
This is now fixed!

**Closed by markusl** 2017-11-20 12:40 UTC

**Comment by luco** [comment] 2017-11-23 23:24
@markusl Thanks a lot!
